### ISSUE TITLE
`Delete (incl. translations)` crashes desk 

### ISSUE THREAD

**Issue by jakubpodolski** [LiamMartens/sanity-plugin-intl-input#72]
Upgrading to the latest release seems to break the `delete (incl. translations)` feature. 
Manually deleting the translated document and then deleting the base language document works as expected

The same crash happens on a fresh project 

### package.json
```
    "@sanity/base": "^2.1.6",
    "@sanity/components": "^2.1.4",
    "@sanity/core": "^2.19.2",
    "@sanity/default-layout": "^2.1.6",
    "@sanity/default-login": "^2.1.4",
    "@sanity/desk-tool": "^2.1.6",
    "@sanity/google-maps-input": "^2.1.6",
    "@sanity/production-preview": "^2.1.4",
    "@sanity/vision": "^2.1.4",
    "prop-types": "^15.7",
    "react": "^17.0",
    "react-dom": "^17.0",
    "sanity-plugin-intl-input": "^5.2.1",
```

### Error 
```
The ‘Desk’ tool crashed

Stack trace:
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `HookStateContainer`.
    at createFiberFromTypeAndProps (/static/js/vendor.bundle.js:27123:21)
    at createFiberFromElement (/static/js/vendor.bundle.js:27146:15)
    at reconcileSingleElement (/static/js/vendor.bundle.js:17391:23)
    at reconcileChildFibers (/static/js/vendor.bundle.js:17451:35)
    at reconcileChildren (/static/js/vendor.bundle.js:19920:28)
    at mountIndeterminateComponent (/static/js/vendor.bundle.js:20700:5)
    at beginWork (/static/js/vendor.bundle.js:21754:16)
    at HTMLUnknownElement.callCallback (/static/js/vendor.bundle.js:3346:14)
    at Object.invokeGuardedCallbackDev (/static/js/vendor.bundle.js:3395:16)
    at invokeGuardedCallback (/static/js/vendor.bundle.js:3450:31)
    
Component stack:
    in ActionStateDialog (created by ActionMenuButton)
    in LayerProvider (created by LegacyLayerProvider)
    in LegacyLayerProvider (created by ActionMenuButton)
    in ActionMenuButton (created by DocumentStatusBarActionsInner)
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box2))
    in ForwardRef(Box2) (created by DocumentStatusBarActionsInner)
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box2))
    in ForwardRef(Box2) (created by Styled(Component))
    in Styled(Component) (created by ForwardRef(Flex2))
    in ForwardRef(Flex2) (created by DocumentStatusBarActionsInner)
    in DocumentStatusBarActionsInner (created by GetHookCollectionState)
    in GetHookCollectionState (created by RenderActionCollectionState)
    in RenderActionCollectionState (created by DocumentStatusBarActions)
    in DocumentStatusBarActions (created by DocumentStatusBar)
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box2))
    in ForwardRef(Box2) (created by Styled(Component))
    in Styled(Component) (created by DocumentStatusBar)
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box2))
    in ForwardRef(Box2) (created by Styled(Component))
    in Styled(Component) (created by ForwardRef(Flex2))
    in ForwardRef(Flex2) (created by DocumentStatusBar)
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box2))
    in ForwardRef(Box2) (created by Styled(Component))
    in Styled(Component) (created by ForwardRef(Card2))
    in Fe (created by ThemeProvider)
    in ThemeProvider (created by ThemeColorProvider)
    in ThemeColorProvider (created by ForwardRef(Card2))
    in ForwardRef(Card2) (created by DocumentStatusBar)
    in DocumentStatusBar (created by DocumentPane)
    in div (created by styled.div)
    in styled.div (created by ForwardRef(LayerChildren2))
    in ForwardRef(LayerChildren2) (created by ForwardRef(Layer2))
    in LayerProvider (created by ForwardRef(Layer2))
    in ForwardRef(Layer2) (created by DocumentPane)
    in LayerProvider (created by LegacyLayerProvider)
    in LegacyLayerProvider (created by DocumentPane)
    in div (created by KeyboardShortcutResponder)
    in KeyboardShortcutResponder (created by GetHookCollectionState)
    in GetHookCollectionState (created by RenderActionCollectionState)
    in RenderActionCollectionState (created by DocumentActionShortcuts)
    in DocumentActionShortcuts (created by DocumentPane)
    in LayerProvider (created by LegacyLayerProvider)
    in LegacyLayerProvider (created by DocumentPane)
    in DocumentPane (created by DocumentPaneProvider)
    in DocumentHistoryProvider (created by DocumentPaneProvider)
    in DocumentPaneProvider
    in StreamingComponent
    in StreamingComponent (created by Context.Consumer)
    in WithInitialValueWrapper (created by DeskToolPane)
    in DeskToolPane (created by DeskToolPanes)
    in SplitPaneWrapper (created by DeskToolPanes)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in PanesSplitController (created by DeskToolPanes)
    in PortalProvider (created by DeskToolPanes)
    in div (created by styled.div)
    in styled.div (created by DeskToolPanes)
    in DeskToolPanes (created by DeskTool)
    in DeskTool (created by withRouter(DeskTool))
    in withRouter(DeskTool) (created by DeskToolPaneStateSyncer)
    in DeskToolPaneStateSyncer (created by DeskTool)
    in DeskToolFeaturesProvider (created by DeskTool)
    in DeskTool (created by RenderTool)
    in RenderTool (created by SchemaErrorReporter)
    in RouteScope (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in SchemaErrorReporter (created by DefaultLayout)
    in DefaultLayout (created by withRouter(DefaultLayout))
    in withRouter(DefaultLayout) (created by DefaultLayoutRoot)
    in RouterProvider (created by DefaultLayoutRoot)
    in LoginWrapper (created by DefaultLayoutRoot)
    in DefaultLayoutRoot (created by AppProvider)
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box2))
    in ForwardRef(Box2) (created by Styled(Component))
    in Styled(Component) (created by ForwardRef(Card2))
    in Fe (created by ThemeProvider)
    in ThemeProvider (created by ThemeColorProvider)
    in ThemeColorProvider (created by ForwardRef(Card2))
    in ForwardRef(Card2) (created by Styled(Component))
    in Styled(Component) (created by AppProvider)
    in SnackbarProvider (created by AppProvider)
    in ToastProvider (created by AppProvider)
    in LayerProvider (created by AppProvider)
    in PortalProvider (created by AppProvider)
    in UserColorManagerProvider (created by AppProvider)
    in AppProvider (created by SanityRoot)
    in Fe (created by ThemeProvider)
    in ThemeProvider (created by SanityRoot)
    in ZIndexProvider (created by SanityRoot)
    in SanityRoot
    in AppContainer

```

**Comment by LiamMartens** [comment]
@jakubpodolski I published  a `beta` version which should fix this - maybe you can confirm
https://www.npmjs.com/package/sanity-plugin-intl-input/v/5.3.0-beta.0

**Comment by lindsaybloomsonos** [comment]
@LiamMartens I am still experiencing this issue after updating to the beta version

**Comment by lindsaybloomsonos** [comment]
@LiamMartens I upgraded to beta `5.3.0-beta.2` and the issue seems to be resolved :)

**Comment by jakubpodolski** [comment]
@LiamMartens Verifed! It works now! Thank you for a quick fix
